=== Genesis2412/ZoomaliaXML/clients.xsd
<?xml version="1.0" encoding="UTF-8"?>
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

        <xs:element name="Clients">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="client">
                        <xs:complexType>
                            <xs:sequence>

                                <xs:element name="Name" type="xs:string"/>
                                <xs:element name="Email" type="xs:string"/>
                                <xs:element name="Phone" type="xs:string"/>

                                <xs:element name="address">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="City" type="xs:string"/>
                                            <xs:element name="Zip" type="xs:positiveInteger"/>
                                            <xs:element name="Address" type="xs:string"/>
                                        </xs:sequence>
                                    </xs:complexType>
                                </xs:element>

                                <xs:element name="bankcard">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="Accountnum" type="xs:positiveInteger"/>
                                            <xs:element name="Expirydate" type="xs:string"/>
                                        </xs:sequence>
                                    </xs:complexType>
                                </xs:element>

                                <xs:element name="product">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="Productname" type="xs:string"/>
                                            <xs:element name="Quantity" type="xs:positiveInteger"/>
                                            <xs:element name="Price" type="xs:decimal"/>
                                            <xs:element name="Image" type="xs:string"/>
                                        </xs:sequence>
                                    </xs:complexType>
                                </xs:element>

                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
                <xs:attribute name="id" type="positiveInteger"/>
            </xs:complexType>
        </xs:element>
    </xs:schema>

=== Genesis2412/ZoomaliaXML/clients.xml
<?xml version="1.0" encoding="utf-8"?>
<Clients xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="clients.xsd">
  <client id="1">
    <Name>Jollo Molo</Name>
    <Email>Molo@polo.com</Email>
    <Phone>59875412</Phone>
    <address>
      <City>SimE grener</City>
      <Zip>78945</Zip>
      <Address>Lalmatie</Address>
    </address>
    <bankcard>
      <Accountnum>74518465489</Accountnum>
      <Expirydate>August 2026</Expirydate>
    </bankcard>
    <product>
      <Productname>Dog Kennel</Productname>
      <Quantity>1</Quantity>
      <Price>1500</Price>
    </product>
  </client>
</Clients>
