=== Genesis2412/ZoomaliaXML/shoplist.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="Products">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="product">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:positiveInteger"/>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="price" type="xs:decimal"/>
                            <xs:element name="img" type="xs:string"/>
                            <xs:element name="description" type="xs:string"/>                            
                        </xs:sequence>

                        <xs:attribute name="category" type="xs:string"/>

                    </xs:complexType>

                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Genesis2412/ZoomaliaXML/shoplist.xml
<?xml version="1.0" encoding="UTF-8"?>
    <Products xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" noNamespaceSchemaLocation="shoplist.xsd">

        <product category="Dress">
            <id>1</id>
            <name>Some test product</name>
            <price>49.00</price>
            <img>product1.jpg</img>
            <description>
                Here comes the description of the test product ...
            </description>
        </product>

        <product category="House">
            <id>2</id>
            <name>Another test product</name>
            <price>69.00</price>
            <img>product2.jpg</img>
            <description>
                This is the description of the second test product ...
            </description>
        </product>
        
    </Products>
